sudo: required
services:
  - docker

before_install:
  - docker build -t thandotettey/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thandotettey/docker-react npm run test -- --coverage
